/**
 * 「悩みから探す」で使う比較候補マスター。
 *
 * 未病レーダーのショップは、対症療法の一般用医薬品ではなく、
 * 続けやすいケア用品・健康食品等と、状態像が合う漢方薬を扱う。
 * 候補理由（why）と商品を選ぶ時の確認（compare）は混ぜない。
 */

export const GUIDED_SCOPE_OPTIONS = [
  { key: "all", label: "まとめて見る", oral: true },
  { key: "selfcare", label: "ケア用品", oral: false },
  { key: "health", label: "健康食品・サプリ", oral: true },
  { key: "kampo", label: "漢方薬", oral: true },
];

export const GUIDED_SCOPE_META = {
  selfcare: { label: "ケア用品", eyebrow: "今日から使う", tone: "mint" },
  health: { label: "健康食品・サプリ", eyebrow: "続け方から選ぶ", tone: "gold" },
  kampo: { label: "漢方薬", eyebrow: "状態の組み合わせから選ぶ", tone: "violet" },
};

export const GUIDED_CLUE_OPTIONS = [
  { key: "after_illness", label: "病後・術後から体力が落ちた", concerns: ["fatigue", "digestion"] },
  { key: "night_sweats", label: "寝汗が気になる", concerns: ["fatigue", "sleep"] },
  { key: "tired_no_sleep", label: "疲れているのに眠れない", concerns: ["sleep", "fatigue"] },
  { key: "irritable", label: "いらだち・神経過敏がある", concerns: ["mood", "sleep"] },
  { key: "sensitive_palpitations", label: "神経過敏で動悸もしやすい", concerns: ["mood", "sleep", "fatigue"] },
  { key: "throat_blocked", label: "喉につかえる感じがある", concerns: ["mood", "digestion", "sleep"] },
  { key: "thirsty_low_urine", label: "口が渇き、尿が少ない", concerns: ["swelling", "headache", "dizziness"] },
  { key: "standing_dizzy_palpitations", label: "立つとふらつき、動悸もある", concerns: ["dizziness", "headache", "mood"] },
  { key: "cold_unsteady", label: "下半身が冷え、ふらつく", concerns: ["dizziness", "fatigue", "swelling"] },
  { key: "sweating_easy", label: "汗をかきやすい", concerns: ["swelling", "fatigue"] },
  { key: "epigastric_nausea", label: "みぞおちがつかえ、吐き気がある", concerns: ["digestion"] },
  { key: "bowel_rumbling_diarrhea", label: "お腹が鳴り、軟便・下痢ぎみ", concerns: ["digestion"] },
  { key: "cold_diarrhea", label: "手足が冷え、下痢しやすい", concerns: ["digestion", "fatigue"] },
  { key: "abdominal_pain_bloat", label: "お腹が張って痛み、便通も変わった", concerns: ["digestion"] },
  { key: "strong_extremity_cold", label: "手足、とくに脚の冷えが強い", concerns: ["fatigue", "headache", "low_back_pain", "swelling"] },
  { key: "shoulder_arm_pain", label: "肩から腕にかけて痛む", concerns: ["neck_shoulder"] },
  { key: "acute_chill_neck", label: "急な寒気と首肩のこわばり", concerns: ["neck_shoulder", "headache"] },
  { key: "muscle_cramp", label: "筋肉が急につる・けいれんする", concerns: ["neck_shoulder", "low_back_pain"] },
];

const C = (candidate) => ({
  answerAnyConditions: [],
  answerConditions: [],
  avoidStates: [],
  caution: "",
  compare: "",
  explicitOnly: false,
  explicitTerms: [],
  ingredientIds: [],
  minCurrentStateMatches: 0,
  minSymptomMatches: 1,
  requiredClues: [],
  anyClues: [],
  persistentOnly: false,
  requiredTextTerms: [],
  ...candidate,
});

export const GUIDED_CANDIDATES = [
  // ケア用品：カテゴリ名ではなく、楽天で比較できる具体的な形状まで分ける。
  C({
    id: "care-neck-heat-wrap", type: "selfcare", productClass: "温熱用品",
    title: "肩甲骨まで覆うレンジ加熱式ネックピロー", query: "レンジ ネックピロー 肩甲骨 温熱",
    symptoms: ["neck_shoulder", "headache"], states: ["cold", "tension", "stagnation"],
    minCurrentStateMatches: 1, direction: "首肩を面で短く温める",
    answerAnyConditions: [{ field: "thermal", values: ["cold", "mixed"] }, { field: "response", values: ["warm_better"] }],
    why: "首だけでなく肩甲骨側まで広く当てられ、温める場所と時間を調整しやすい形状です。",
    compare: "加熱時間、保温時間、重さ、首周りの寸法、カバーを洗えるかを比べます。",
    caution: "熱感・腫れ・急な痛みがある場所には使わず、就寝中の使用と低温やけどに注意してください。",
  }),
  C({
    id: "care-neck-cool-wrap", type: "selfcare", productClass: "冷却用品",
    title: "首肩へ固定できるジェル冷却ラップ", query: "首肩 ジェル 冷却 ラップ 固定",
    symptoms: ["neck_shoulder", "headache"], states: ["heat", "tension"],
    minCurrentStateMatches: 1, direction: "熱感のある首肩を短く冷やす",
    answerAnyConditions: [{ field: "thermal", values: ["heat", "mixed"] }],
    why: "保冷剤を手で押さえず、首肩へ短時間固定しやすい形状です。",
    compare: "冷却時間、凍っても硬くなりにくいか、固定方法、結露しにくさを比べます。",
    caution: "突然の激しい頭痛、しびれ、麻痺がある場合はセルフケアを優先しません。",
  }),
  C({
    id: "care-massage-ball", type: "selfcare", productClass: "セルフリリース用品",
    title: "壁で圧を調整できるソフトマッサージボール", query: "ソフト マッサージボール 壁 首肩 腰",
    symptoms: ["neck_shoulder", "low_back_pain"], states: ["stagnation", "tension"],
    minCurrentStateMatches: 1, direction: "壁を使って狭い範囲の圧を調整する",
    why: "床で体重をかけすぎず、壁との距離で圧を弱く調整できる用品です。",
    compare: "直径、硬さ、滑りにくさ、2個連結型か単球かを比べます。",
    caution: "首の前面・骨の真上・急な痛みやしびれがある場所には使用しません。",
  }),
  C({
    id: "care-soft-foam-roller", type: "selfcare", productClass: "セルフリリース用品",
    title: "突起の少ないソフトフォームローラー", query: "ソフト フォームローラー 突起なし",
    symptoms: ["fatigue", "neck_shoulder", "low_back_pain"], states: ["stagnation", "tension"],
    minCurrentStateMatches: 1, direction: "広い範囲を弱い圧で短く動かす",
    why: "硬い突起へ一点集中させず、背中や脚を広い面で動かしやすい形です。",
    compare: "表面の凹凸、硬さ、直径、長さ、耐荷重を比べます。",
    caution: "急な痛み、骨折・手術後、感覚低下がある部位には自己判断で使いません。",
  }),
  C({
    id: "care-calf-roller", type: "selfcare", productClass: "セルフリリース用品",
    title: "手で圧を加減できるふくらはぎローラー", query: "ふくらはぎ ローラー 手持ち 圧調整",
    symptoms: ["swelling", "fatigue"], states: ["damp", "stagnation"],
    minCurrentStateMatches: 1, direction: "脚を強く押さず短時間動かす",
    why: "体重を載せず、手元で圧を止めたり弱めたりできる形状です。",
    compare: "ローラーの硬さ、挟む幅、持ち手、皮膚を巻き込みにくいかを比べます。",
    caution: "片脚だけの急な腫れ・熱・痛み、血栓症の既往がある場合は使用を避けて相談してください。",
  }),
  C({
    id: "care-light-compression-socks", type: "selfcare", productClass: "着圧用品",
    title: "弱圧タイプの段階着圧ソックス", query: "弱圧 段階着圧 ソックス",
    symptoms: ["swelling", "fatigue"], states: ["damp"],
    minCurrentStateMatches: 1, direction: "日中の脚の重さを支える",
    why: "強圧から始めず、足首から上へ圧が変わる製品を比較する候補です。",
    compare: "足首の圧力表示、サイズ表、丈、つま先の有無、医療機器表示を比べます。",
    caution: "動脈血流障害、糖尿病性末梢神経障害、皮膚炎、急な片脚の腫れがある場合は購入前に専門家へ確認してください。",
  }),
  C({
    id: "care-foot-bath-bucket", type: "selfcare", productClass: "温浴用品",
    title: "ふくらはぎ下まで入る保温ふた付き足浴バケツ", query: "足浴 バケツ 保温 ふた 深型",
    symptoms: ["fatigue", "swelling", "sleep"], states: ["cold", "recovery_low"],
    minCurrentStateMatches: 1, direction: "足元から短時間温める",
    answerAnyConditions: [{ field: "thermal", values: ["cold", "mixed"] }, { field: "response", values: ["warm_better"] }],
    why: "足首だけでなくふくらはぎ下まで入れやすく、湯温低下を抑えやすい形です。",
    compare: "内寸、深さ、保温ふた、持ち手、排水のしやすさを比べます。",
    caution: "感覚低下、循環障害、皮膚トラブルがある場合は温度管理を含め専門家へ確認してください。",
  }),
  C({
    id: "care-ankle-warmer", type: "selfcare", productClass: "保温用品",
    title: "締め付けにくい足首ウォーマー", query: "足首 ウォーマー 締め付けない",
    symptoms: ["fatigue", "swelling", "sleep"], states: ["cold"],
    minCurrentStateMatches: 1, direction: "冷える足首を日中に保温する",
    answerAnyConditions: [{ field: "thermal", values: ["cold", "mixed"] }],
    why: "全身を厚着せず、冷えを感じる足首だけを保温しやすい用品です。",
    compare: "履き口の伸び、素材、丈、洗濯方法、靴と干渉しない厚さを比べます。",
  }),
  C({
    id: "care-abdominal-heat-pad", type: "selfcare", productClass: "温熱用品",
    title: "腹部へ沿うレンジ加熱式温熱パッド", query: "腹部 温熱パッド レンジ 繰り返し",
    symptoms: ["digestion", "fatigue", "low_back_pain"], states: ["cold", "digestive_weak"],
    minCurrentStateMatches: 1, direction: "腹部を短時間やさしく温める",
    answerAnyConditions: [{ field: "thermal", values: ["cold", "mixed"] }, { field: "response", values: ["warm_better"] }],
    why: "腹部の曲面へ沿い、温める範囲と時間を調整しやすい形状です。",
    compare: "大きさ、重さ、加熱時間、保温時間、洗えるカバーを比べます。",
    caution: "強い腹痛、発熱、嘔吐、妊娠中、感覚低下がある場合は自己判断で使いません。",
  }),
  C({
    id: "care-sleep-eye-mask", type: "selfcare", productClass: "睡眠環境用品",
    title: "まぶたへ触れにくい立体遮光アイマスク", query: "立体 遮光 アイマスク 圧迫しない",
    symptoms: ["sleep", "headache", "fatigue"], states: ["tension", "recovery_low", "heat"],
    minCurrentStateMatches: 1, direction: "夜の光刺激を減らす",
    why: "光を遮りながら、まぶたや眼球周囲への圧迫を避けやすい形です。",
    compare: "鼻周りの遮光、目元の空間、バンド調整、寝返り時のずれ、洗いやすさを比べます。",
  }),
  C({
    id: "care-sleep-earplugs", type: "selfcare", productClass: "睡眠環境用品",
    title: "横向きでも当たりにくい睡眠用ソフト耳栓", query: "睡眠用 耳栓 ソフト 横向き",
    symptoms: ["sleep", "headache", "fatigue"], states: ["tension", "recovery_low"],
    minCurrentStateMatches: 1, direction: "夜の突発音を減らす",
    why: "横向き寝で耳へ当たりにくく、睡眠中の音刺激を減らす用途に絞った用品です。",
    compare: "遮音値、素材、サイズ、洗えるか、目覚まし音が聞こえるかを比べます。",
    caution: "耳の痛み・炎症がある場合は使用せず、必要な警報音まで遮らないようにしてください。",
  }),
  C({
    id: "care-steam-eye-mask", type: "selfcare", productClass: "温熱用品",
    title: "温度表示のある蒸気温熱アイマスク", query: "蒸気 温熱 アイマスク 温度表示",
    symptoms: ["sleep", "headache", "fatigue"], states: ["cold", "tension", "recovery_low"], avoidStates: ["heat"],
    minCurrentStateMatches: 1, direction: "目元を短時間温めて休止の合図を作る",
    why: "使用温度と時間を確認しやすく、目元を短時間休ませる用途が明確な用品です。",
    compare: "温度と持続時間、香料の有無、耳かけの圧、個包装かを比べます。",
    caution: "目の炎症、手術後、温感が分かりにくい場合は使用前に専門家へ確認してください。",
  }),
  C({
    id: "care-humid-meter", type: "selfcare", productClass: "環境計測用品",
    title: "最高・最低値を記録できるデジタル温湿度計", query: "温湿度計 最高最低 記録 デジタル",
    symptoms: ["sleep", "fatigue", "headache", "dizziness", "swelling"], states: ["damp", "dry", "heat", "cold"],
    minCurrentStateMatches: 1, direction: "室内の温度と湿度を見える化する",
    why: "現在値だけでなく、寝室や仕事場の一日の振れ幅を後から確認できる用品です。",
    compare: "表示の見やすさ、最高・最低値の保存、更新間隔、置き方、精度表示を比べます。",
  }),
  C({
    id: "care-lumbar-support", type: "selfcare", productClass: "姿勢補助用品",
    title: "高さを調整できるランバーサポートクッション", query: "ランバーサポート クッション 高さ調整",
    symptoms: ["low_back_pain", "fatigue"], states: ["tension", "stagnation"],
    minCurrentStateMatches: 1, direction: "座位の支点を変えやすくする",
    why: "中材や取り付け位置を変え、椅子ごとに腰の支点を調整できる用品です。",
    compare: "高さ調整、椅子との寸法、硬さ、固定ベルト、カバーを洗えるかを比べます。",
    caution: "強い痛みや脚のしびれ、排尿・排便の異常がある場合は受診を優先してください。",
  }),
  C({
    id: "care-seat-cushion", type: "selfcare", productClass: "姿勢補助用品",
    title: "前後を入れ替えられる体圧分散シートクッション", query: "体圧分散 シートクッション 前後 入れ替え",
    symptoms: ["low_back_pain", "fatigue"], states: ["tension", "stagnation"],
    minCurrentStateMatches: 1, direction: "座面の圧を分散し姿勢を固定しすぎない",
    why: "同じ座面形状へ固定せず、向きや位置を変えて圧のかかり方を調整できます。",
    compare: "座面寸法、厚さ、沈み込み、滑り止め、カバーの洗濯可否を比べます。",
  }),
  C({
    id: "care-fireless-moxa", type: "selfcare", productClass: "温熱刺激用品",
    title: "火を使わない貼るタイプのお灸", query: "火を使わない お灸 貼るタイプ",
    symptoms: ["fatigue", "digestion", "neck_shoulder", "low_back_pain"], states: ["cold", "tension"],
    minCurrentStateMatches: 1, direction: "火を使わず局所を短時間温める",
    answerAnyConditions: [{ field: "thermal", values: ["cold", "mixed"] }, { field: "response", values: ["warm_better"] }],
    why: "煙や火を避けながら、貼付位置と使用時間を決めて温熱刺激を試せる用品です。",
    compare: "最高温度、持続時間、粘着部、使用部位、低温タイプの有無を比べます。",
    caution: "就寝中、顔面、炎症部位、感覚低下部位には使用しません。妊娠中や治療中は使用部位を専門家へ確認してください。",
  }),

  // 健康食品・サプリ：継続する状態、または成分名の明示がある時だけ候補にする。
  C({
    id: "health-ginger-drink", type: "health", productClass: "健康飲料",
    title: "しょうがを使った健康飲料", query: "しょうが 健康飲料",
    symptoms: ["fatigue", "digestion", "neck_shoulder"], states: ["cold", "digestive_weak"], avoidStates: ["heat"],
    minCurrentStateMatches: 2, explicitTerms: ["しょうが", "生姜", "ジンジャー"], direction: "冷たい飲み物の連続を切る",
    why: "冷えと胃腸の負担が重なり、温かい飲み物へ切り替える選択肢を持ちたい時の候補です。",
    compare: "しょうがの表示、糖分、カフェイン、1回量、毎日続けられる味かを比べます。",
    caution: "辛味で胃がつらくなる人や、治療中・服薬中の人は原材料と取り方を確認してください。",
    ingredientIds: ["ginger"],
  }),
  C({
    id: "health-nutrition-drink", type: "health", productClass: "栄養補助飲料",
    title: "少量高エネルギー型の栄養補助飲料", query: "少量 高エネルギー 栄養補助飲料",
    symptoms: ["fatigue", "digestion", "dizziness"], states: ["energy_low", "digestive_weak", "recovery_low"],
    minCurrentStateMatches: 2,
    answerConditions: [{ field: "digestion", values: ["appetite_low"] }],
    direction: "食べられない日の不足を重ねない",
    why: "疲れやすさに食欲低下が重なり、通常の食事を取りにくい日の補助を探す条件です。",
    compare: "1本の容量とエネルギー、たんぱく質、糖質、アレルゲン、飲み切れる量を比べます。",
    caution: "食欲低下が続く、体重が減る、食事制限がある場合は商品選びより原因確認を優先してください。",
  }),
  C({
    id: "health-ginseng", type: "health", productClass: "生薬系健康食品",
    title: "高麗人参（オタネニンジン）", query: "高麗人参 健康食品",
    symptoms: ["fatigue"], states: ["energy_low", "cold"], avoidStates: ["heat", "tension"],
    minCurrentStateMatches: 2, persistentOnly: true, explicitTerms: ["高麗人参", "オタネニンジン", "人参サプリ"],
    direction: "疲れやすさが続く時の健康食品を比較する",
    why: "疲れやすさが続き、体力低下と冷えが重なる場合に、生薬系健康食品として比較する候補です。",
    compare: "使用部位、抽出物か粉末か、1日量、同時配合成分、カフェインの有無を比べます。",
    caution: "不眠・動悸がある人、血圧・血糖の治療中、抗凝固薬などを使用中の人は専門家へ確認してください。",
    ingredientIds: ["ginseng_root"],
  }),
  C({
    id: "health-coix", type: "health", productClass: "生薬系健康食品",
    title: "ハトムギ由来の健康食品", query: "ハトムギ 健康食品",
    symptoms: ["swelling"], states: ["damp"], minCurrentStateMatches: 1, persistentOnly: true,
    explicitTerms: ["ハトムギ", "ヨクイニン"], direction: "重さやむくみ感が続く時の素材を比較する",
    why: "むくみ感と重さがしばらく続く場合に、ハトムギ由来の健康食品を比較する候補です。",
    compare: "食品・健康食品・医薬品の区分、使用部位、1日量、ほかの原料との組み合わせを比べます。",
    caution: "むくみの治療代わりにはしません。妊娠中、片脚だけの腫れ、息苦しさを伴う場合は自己判断で使わないでください。",
    ingredientIds: ["coix_seed"],
  }),
  C({
    id: "health-duzhong", type: "health", productClass: "健康茶",
    title: "杜仲葉を使った健康茶", query: "杜仲茶",
    symptoms: ["fatigue", "swelling"], states: ["damp", "energy_low"],
    explicitOnly: true, explicitTerms: ["杜仲", "杜仲茶", "杜仲葉"], direction: "杜仲葉の健康茶を区分して比較する",
    why: "杜仲を調べたいという入力がある場合に、樹皮を使う生薬とは区別して健康茶を比較します。",
    compare: "杜仲葉の表示、単一原料かブレンドか、カフェイン、抽出方法、1日量を比べます。",
    caution: "治療中・服薬中、妊娠・授乳中は使用前に専門家へ確認してください。",
    ingredientIds: ["eucommia_leaf"],
  }),
  C({
    id: "health-heme-iron", type: "health", productClass: "サプリメント",
    title: "ヘム鉄", query: "ヘム鉄 サプリ",
    symptoms: ["fatigue", "dizziness"], states: ["energy_low", "recovery_low"],
    explicitOnly: true, explicitTerms: ["ヘム鉄", "鉄サプリ"], direction: "鉄を補う前に必要性と重複を確認する",
    why: "ヘム鉄・鉄サプリを調べたいという入力があるため、体感だけで不足と決めず比較対象にします。",
    compare: "1日量、鉄以外の配合成分、ほかのサプリとの重複、続けやすい剤形を比べます。",
    caution: "疲れやめまいだけで鉄不足とは判断できません。強い症状、妊娠中、治療中は検査や専門家確認を優先してください。",
    ingredientIds: ["iron"],
  }),
  C({
    id: "health-magnesium", type: "health", productClass: "サプリメント",
    title: "マグネシウム", query: "マグネシウム サプリ",
    symptoms: ["sleep", "neck_shoulder", "mood", "headache"], states: ["tension", "recovery_low"],
    explicitOnly: true, explicitTerms: ["マグネシウム"], direction: "不足を決めつけず成分を比較する",
    why: "マグネシウムを調べたいという入力があるため、症状だけで不足と決めず比較対象にします。",
    compare: "1日量、化合物の種類、ほかのサプリとの重複、摂取回数を比べます。",
    caution: "下痢を起こすことがあります。腎機能低下や治療中・服薬中の場合は事前に専門家へ確認してください。",
    ingredientIds: ["magnesium"],
  }),
  C({
    id: "health-b-vitamins", type: "health", productClass: "サプリメント",
    title: "ビタミンB群", query: "ビタミンB群 サプリ",
    symptoms: ["fatigue", "digestion"], states: ["energy_low", "recovery_low"],
    explicitOnly: true, explicitTerms: ["ビタミンB", "B群サプリ"], direction: "食事と他製品の重複を確認する",
    why: "ビタミンB群を調べたいという入力があるため、食事状況と重複を確認する比較対象にします。",
    compare: "各ビタミンの1日量、単一成分か複合か、栄養ドリンクやマルチビタミンとの重複を比べます。",
    caution: "複数製品を併用する場合は、同じビタミンを重ねていないか確認してください。",
    ingredientIds: ["vitamin_b_group"],
  }),
  C({
    id: "health-ginkgo", type: "health", productClass: "植物由来サプリ",
    title: "イチョウ葉エキス", query: "イチョウ葉 サプリ",
    symptoms: ["dizziness", "mood"], states: ["stagnation"],
    explicitOnly: true, explicitTerms: ["イチョウ葉", "銀杏葉"], direction: "目的と安全条件を確認して比較する",
    why: "イチョウ葉を調べたいという入力があるため、症状の治療代わりにせず比較対象にします。",
    compare: "原料表示、抽出物の表示、1日量、同時配合成分を比べます。",
    caution: "出血リスクに関係する薬との相互作用があります。めまいが続く場合は原因確認を優先してください。",
    ingredientIds: ["ginkgo_leaf"],
  }),
  C({
    id: "health-turmeric", type: "health", productClass: "植物由来サプリ",
    title: "ウコン由来の健康食品", query: "ウコン サプリ",
    symptoms: ["digestion", "fatigue"], states: ["stagnation"],
    explicitOnly: true, explicitTerms: ["ウコン", "クルクミン"], direction: "飲酒対策と決めつけず比較する",
    why: "ウコン・クルクミンを調べたいという入力があるため、利用目的を確認する比較対象にします。",
    compare: "原料部位、クルクミンの表示、1日量、同時配合成分を比べます。",
    caution: "胆道疾患・肝疾患がある人、抗凝固薬などを使用中の人は自己判断で使わないでください。",
    ingredientIds: ["turmeric_rhizome"],
  }),
  C({
    id: "health-maca", type: "health", productClass: "植物由来サプリ",
    title: "マカ", query: "マカ サプリ",
    symptoms: ["fatigue", "mood"], states: ["energy_low"],
    explicitOnly: true, explicitTerms: ["マカ"], direction: "商品名の印象ではなく中身を比較する",
    why: "マカを調べたいという入力があるため、疲労の原因を決めつけず比較対象にします。",
    compare: "マカ原料の1日量、抽出物か粉末か、同時配合成分、カフェインの有無を比べます。",
    caution: "妊娠・授乳中、治療中、ホルモンに関係する疾患がある場合は専門家へ確認してください。",
    ingredientIds: ["maca_root"],
  }),
  C({
    id: "health-eleuthero", type: "health", productClass: "生薬系健康食品",
    title: "エゾウコギ由来の健康食品", query: "エゾウコギ 健康食品",
    symptoms: ["fatigue"], states: ["energy_low", "recovery_low", "cold"], avoidStates: ["heat", "tension"],
    minCurrentStateMatches: 2, persistentOnly: true,
    answerConditions: [{ field: "reserve", values: ["low"] }],
    direction: "長引く疲れと体力低下から生薬系素材を比較する",
    why: "疲れやすさが続き、今の体力が落ちている回答から、生薬系健康食品として比較する候補です。",
    compare: "使用部位、抽出物か粉末か、1日量、同時配合成分、カフェインの有無を比べます。",
    caution: "不眠・動悸・高血圧がある人、妊娠・授乳中、治療中・服薬中の人は専門家へ確認してください。",
    ingredientIds: ["eleuthero_root"],
  }),
  C({
    id: "health-gaba-functional", type: "health", productClass: "機能性表示食品",
    title: "GABAを含む機能性表示食品", query: "GABA 機能性表示食品 睡眠",
    symptoms: ["sleep", "mood"], states: ["tension", "recovery_low"],
    minCurrentStateMatches: 2, persistentOnly: true, anyClues: ["tired_no_sleep", "irritable"],
    direction: "届出表示が今の目的と一致するGABA製品を比較する",
    why: "睡眠または気分の負担が続き、追加回答の状態と届出表示を照合する候補です。",
    compare: "届出表示の対象、機能性関与成分量、摂取時期、糖質、ほかのGABA製品との重複を比べます。",
    caution: "GABAを含むだけの商品と機能性表示食品を区別してください。治療中・服薬中は専門家へ確認してください。",
    ingredientIds: ["gaba"],
  }),
  C({
    id: "health-theanine-functional", type: "health", productClass: "機能性表示食品",
    title: "L-テアニンを含む機能性表示食品", query: "L-テアニン 機能性表示食品 睡眠",
    symptoms: ["sleep", "mood"], states: ["tension", "recovery_low"],
    minCurrentStateMatches: 2, persistentOnly: true, anyClues: ["tired_no_sleep", "irritable"],
    direction: "睡眠・一時的なストレスに関する届出表示を見分ける",
    why: "睡眠または気分の負担が続き、追加回答の状態と届出表示を照合する候補です。",
    compare: "届出表示の対象、L-テアニン量、摂取時期、カフェインの有無、同時配合成分を比べます。",
    caution: "商品ごとに届出表示が異なります。眠気に関係する薬を使用中の場合は専門家へ確認してください。",
    ingredientIds: ["l_theanine"],
  }),
  C({
    id: "health-glycine-functional", type: "health", productClass: "機能性表示食品",
    title: "グリシンを含む睡眠系機能性表示食品", query: "グリシン 機能性表示食品 睡眠",
    symptoms: ["sleep", "fatigue"], states: ["recovery_low"],
    minCurrentStateMatches: 1, persistentOnly: true, anyClues: ["tired_no_sleep"],
    direction: "睡眠の質に関する届出表示を確認する",
    why: "疲れているのに眠りにくい状態が続く回答から、睡眠に関する届出表示を比較する候補です。",
    compare: "届出表示、グリシン量、摂取時期、甘味料、ほかのアミノ酸製品との重複を比べます。",
    caution: "不眠が長引く、日中生活へ影響する場合は健康食品だけで対応しないでください。",
    ingredientIds: ["glycine"],
  }),
  C({
    id: "health-bifidobacteria-functional", type: "health", productClass: "機能性表示食品",
    title: "菌株を明記したビフィズス菌の機能性表示食品", query: "ビフィズス菌 菌株 機能性表示食品",
    symptoms: ["digestion"], states: ["digestive_weak"],
    minCurrentStateMatches: 1, persistentOnly: true,
    answerConditions: [{ field: "digestion", values: ["bowel_change"] }],
    direction: "便通の変化と届出表示が合う菌株を比較する",
    why: "便通の変化が続く回答から、菌株と届出表示を確認できる製品を比較する候補です。",
    compare: "菌株名、届出表示、1日量、保存方法、オリゴ糖等の同時配合を比べます。",
    caution: "血便、発熱、体重減少、強い腹痛を伴う便通変化は商品選びより受診を優先してください。",
    ingredientIds: ["bifidobacteria"],
  }),
  C({
    id: "health-notoginseng", type: "health", productClass: "生薬系健康食品",
    title: "田七人参（サンシチニンジン）", query: "田七人参 健康食品",
    symptoms: ["fatigue", "mood"], states: ["stagnation"],
    explicitOnly: true, explicitTerms: ["田七人参", "三七人参", "サンシチニンジン"],
    direction: "田七人参を単味か配合品かで比較する",
    why: "田七人参を調べたいという入力があるため、原料と安全条件を確認する比較対象にします。",
    compare: "原料名、使用部位、抽出物か粉末か、1日量、同時配合成分を比べます。",
    caution: "抗凝固薬・抗血小板薬などを使用中、妊娠・授乳中、出血しやすい人は自己判断で使わないでください。",
    ingredientIds: ["notoginseng_root"],
  }),
  C({
    id: "health-black-ginger", type: "health", productClass: "機能性表示食品",
    title: "ブラックジンジャー由来成分の機能性表示食品", query: "ブラックジンジャー 機能性表示食品",
    symptoms: ["fatigue"], states: ["energy_low"],
    explicitOnly: true, explicitTerms: ["ブラックジンジャー", "黒しょうが", "黒ショウガ"],
    direction: "商品ごとの届出機能を確認して比較する",
    why: "ブラックジンジャーを調べたいという入力があるため、商品ごとに異なる届出表示を確認する対象にします。",
    compare: "機能性関与成分、届出表示、1日量、同時配合成分、摂取期間を比べます。",
    caution: "疲労全般に使える成分とは限りません。疾病の治療中・服薬中は専門家へ確認してください。",
    ingredientIds: ["black_ginger"],
  }),
  C({
    id: "health-salacia", type: "health", productClass: "機能性表示食品",
    title: "サラシア由来成分の機能性表示食品", query: "サラシア 機能性表示食品",
    symptoms: ["digestion"], states: ["digestive_weak", "damp"],
    explicitOnly: true, explicitTerms: ["サラシア"],
    direction: "食後に関する届出表示を確認する",
    why: "サラシアを調べたいという入力があるため、利用目的と届出表示を確認する対象にします。",
    compare: "機能性関与成分、届出表示、摂取時期、1日量、糖質制限薬等との併用を比べます。",
    caution: "糖尿病治療中、妊娠・授乳中、低血糖を起こしやすい人は自己判断で使用しないでください。",
    ingredientIds: ["salacia"],
  }),
  C({
    id: "health-mulberry-leaf", type: "health", productClass: "機能性表示食品",
    title: "桑葉由来成分の機能性表示食品", query: "桑葉 機能性表示食品",
    symptoms: ["digestion"], states: ["digestive_weak"],
    explicitOnly: true, explicitTerms: ["桑葉", "桑の葉"],
    direction: "桑葉の原料表示と届出機能を確認する",
    why: "桑葉を調べたいという入力があるため、健康茶と機能性表示食品を区分して比較します。",
    compare: "機能性関与成分、届出表示、桑葉量、摂取時期、同時配合成分を比べます。",
    caution: "糖尿病治療中、低血糖を起こしやすい人、妊娠・授乳中は専門家へ確認してください。",
    ingredientIds: ["mulberry_leaf"],
  }),
  C({
    id: "health-goji", type: "health", productClass: "植物由来健康食品",
    title: "クコの実由来の健康食品", query: "クコの実 健康食品",
    symptoms: ["fatigue"], states: ["dry", "recovery_low"],
    explicitOnly: true, explicitTerms: ["クコ", "枸杞", "ゴジベリー"],
    direction: "食品素材としてのクコと濃縮製品を分ける",
    why: "クコを調べたいという入力があるため、通常食品と濃縮した健康食品を分けて比較します。",
    compare: "果実か抽出物か、1日量、糖質、原産地、同時配合成分を比べます。",
    caution: "ワルファリン等との相互作用が報告されています。治療中・服薬中は専門家へ確認してください。",
    ingredientIds: ["goji_fruit"],
  }),

  // 漢方薬：現在の複数条件が処方像と重なる場合だけ候補にする。
  C({
    id: "kampo-hochuekkito", type: "kampo", productClass: "第2類医薬品",
    title: "補中益気湯", query: "補中益気湯 第2類医薬品",
    symptoms: ["fatigue", "digestion"], states: ["energy_low", "digestive_weak", "recovery_low"], avoidStates: ["heat"],
    minCurrentStateMatches: 2, persistentOnly: true,
    answerConditions: [{ field: "reserve", values: ["low"] }, { field: "digestion", values: ["appetite_low", "postmeal_heavy"] }],
    direction: "疲れやすさと胃腸の弱りを一緒に確認する",
    why: "疲れやすさ、体力低下、食欲・胃腸の弱りが重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた体力傾向、1日量、剤形、甘草を含む他製品との重複を確認します。",
    caution: "甘草を含みます。高血圧、むくみ、心・腎疾患、治療中・服薬中の場合は薬剤師等へ確認してください。",
    ingredientIds: ["formula_hochuekkito", "licorice_root", "ginseng_root", "astragalus_root"],
  }),
  C({
    id: "kampo-rikkunshito", type: "kampo", productClass: "第2類医薬品",
    title: "六君子湯", query: "六君子湯 第2類医薬品",
    symptoms: ["digestion", "fatigue"], states: ["digestive_weak", "energy_low", "damp"],
    minCurrentStateMatches: 2,
    answerConditions: [{ field: "digestion", values: ["appetite_low", "postmeal_heavy"] }],
    direction: "胃腸の弱りと食欲を確認する",
    why: "胃腸の不調に、食欲低下・食後の重さと体力低下が重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた胃腸症状と体力傾向、剤形、1日量、甘草の重複を確認します。",
    caution: "甘草を含みます。治療中・服薬中、持病がある場合は薬剤師等へ確認してください。",
    ingredientIds: ["formula_rikkunshito", "licorice_root", "ginseng_root"],
  }),
  C({
    id: "kampo-goreisan", type: "kampo", productClass: "第2類医薬品",
    title: "五苓散", query: "五苓散 第2類医薬品",
    symptoms: ["swelling", "headache", "dizziness"], states: ["damp"], avoidStates: ["dry"],
    minCurrentStateMatches: 1,
    anyClues: ["thirsty_low_urine"],
    requiredTextTerms: ["口渇", "のどが渇", "喉が渇", "尿が少ない", "水を飲むと吐"],
    explicitTerms: ["五苓散"], direction: "水分の偏りと口渇・尿量を確認する",
    why: "むくみ・頭痛・めまいだけでなく、口渇や尿量など水分の偏りを示す入力がある時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた口渇・尿量等の条件、剤形、1日量を確認します。",
    caution: "長引くめまい・頭痛・嘔吐、急なむくみは商品探しより原因確認を優先してください。",
    ingredientIds: ["formula_goreisan"],
  }),
  C({
    id: "kampo-boiogito", type: "kampo", productClass: "第2類医薬品",
    title: "防已黄耆湯", query: "防已黄耆湯 第2類医薬品",
    symptoms: ["swelling", "fatigue"], states: ["damp", "energy_low"],
    minCurrentStateMatches: 2, persistentOnly: true,
    anyClues: ["sweating_easy"],
    requiredTextTerms: ["汗をかきやすい", "汗かき"], explicitTerms: ["防已黄耆湯"],
    direction: "むくみ・疲れやすさ・汗のかき方を確認する",
    why: "むくみ感、疲れやすさ、汗をかきやすい体力傾向が重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた体力・汗・むくみの条件、剤形、甘草の重複を確認します。",
    caution: "甘草を含みます。高血圧、心・腎疾患、治療中・服薬中の場合は薬剤師等へ確認してください。",
    ingredientIds: ["formula_boiogito", "licorice_root", "astragalus_root"],
  }),
  C({
    id: "kampo-kamikihito", type: "kampo", productClass: "第2類医薬品",
    title: "加味帰脾湯", query: "加味帰脾湯 第2類医薬品",
    symptoms: ["sleep", "mood", "fatigue"], states: ["energy_low", "recovery_low", "tension"],
    minCurrentStateMatches: 2, minSymptomMatches: 2, persistentOnly: true,
    direction: "疲労・不安感・睡眠をまとめて確認する",
    why: "心身の疲れに、睡眠の乱れや不安感が複数重なる時に体力傾向と適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた精神症状と体力傾向、剤形、甘草の重複を確認します。",
    caution: "甘草を含みます。妊娠中、治療中・服薬中の場合は薬剤師等へ確認してください。",
    ingredientIds: ["formula_kamikihito", "licorice_root", "ginseng_root", "astragalus_root"],
  }),
  C({
    id: "kampo-sansoninto", type: "kampo", productClass: "第2類医薬品",
    title: "酸棗仁湯", query: "酸棗仁湯 第2類医薬品",
    symptoms: ["sleep", "fatigue"], states: ["recovery_low", "energy_low", "tension"],
    minCurrentStateMatches: 2, minSymptomMatches: 1, persistentOnly: true,
    anyClues: ["tired_no_sleep"],
    answerConditions: [{ field: "reserve", values: ["low"] }],
    direction: "疲れているのに眠れない状態を確認する",
    why: "睡眠の乱れに、疲れや体力低下が続く状態が重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた不眠と体力傾向、剤形、1日量、甘草の重複を確認します。",
    caution: "甘草を含む製品があります。長引く不眠や日中機能低下は受診も検討してください。",
    ingredientIds: ["formula_sansoninto", "licorice_root"],
  }),
  C({
    id: "kampo-hangekobokuto", type: "kampo", productClass: "第2類医薬品",
    title: "半夏厚朴湯", query: "半夏厚朴湯 第2類医薬品",
    symptoms: ["mood", "digestion", "sleep"], states: ["tension", "stagnation"],
    minCurrentStateMatches: 2,
    anyClues: ["throat_blocked"],
    requiredTextTerms: ["喉がつかえる", "のどがつかえる", "喉の異物感", "梅核気"], explicitTerms: ["半夏厚朴湯"],
    direction: "喉のつかえ感と気分の緊張を確認する",
    why: "気分の負担に、喉や食道部のつかえ感が重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた喉のつかえ感と体力傾向、剤形、1日量を確認します。",
    caution: "飲み込みづらさが続く、体重減少、胸痛がある場合は自己判断を避けてください。",
    ingredientIds: ["formula_hangekobokuto", "ginger"],
  }),
  C({
    id: "kampo-anchusan", type: "kampo", productClass: "第2類医薬品",
    title: "安中散", query: "安中散 第2類医薬品",
    symptoms: ["digestion"], states: ["cold", "digestive_weak"], avoidStates: ["heat"],
    minCurrentStateMatches: 2,
    answerConditions: [{ field: "digestion", values: ["appetite_low", "postmeal_heavy"] }],
    direction: "冷えを伴う胃の不調を確認する",
    why: "胃腸の不調に、冷えと食欲・食後の変化が重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた胃痛・胸やけ等の症状、体力傾向、甘草の重複を確認します。",
    caution: "黒い便、吐血、強い腹痛がある場合は受診を優先してください。",
    ingredientIds: ["formula_anchusan", "licorice_root"],
  }),
  C({
    id: "kampo-kakkonto", type: "kampo", productClass: "第2類医薬品",
    title: "葛根湯", query: "葛根湯 第2類医薬品",
    symptoms: ["neck_shoulder", "headache"], states: ["cold", "tension"], avoidStates: ["heat", "energy_low"],
    minCurrentStateMatches: 2, allowedDurations: ["today", "days"],
    anyClues: ["acute_chill_neck"],
    requiredTextTerms: ["寒気", "ぞくぞく", "風邪", "かぜ"], explicitTerms: ["葛根湯"],
    direction: "急な寒気と首肩のこわばりを確認する",
    why: "慢性的な肩こりではなく、急な寒気・かぜの初期と首肩のこわばりが重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた発症時期・発汗・体力傾向、麻黄・甘草の重複を確認します。",
    caution: "麻黄・甘草を含みます。高血圧、心疾患、甲状腺疾患、排尿困難、治療中・服薬中の場合は薬剤師等へ確認してください。",
    ingredientIds: ["formula_kakkonto", "ephedra_herb", "licorice_root", "ginger", "kudzu_root"],
  }),
  C({
    id: "kampo-tokishakuyakusan", type: "kampo", productClass: "第2類医薬品",
    title: "当帰芍薬散", query: "当帰芍薬散 第2類医薬品",
    symptoms: ["dizziness", "swelling", "fatigue"], states: ["cold", "energy_low", "damp"],
    minCurrentStateMatches: 3, minSymptomMatches: 2, persistentOnly: true,
    direction: "冷え・体力・めまい・むくみの組み合わせを確認する",
    why: "冷えと体力低下に、めまい・むくみなどが複数重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた体力・冷え・めまい等の条件、剤形、1日量を確認します。",
    caution: "めまいの原因確認が先です。妊娠中、治療中・服薬中の場合は専門家へ確認してください。",
    ingredientIds: ["formula_tokishakuyakusan", "peony_root"],
  }),
  C({
    id: "kampo-shakuyakukanzoto", type: "kampo", productClass: "第2類医薬品",
    title: "芍薬甘草湯", query: "芍薬甘草湯 第2類医薬品",
    symptoms: ["low_back_pain", "neck_shoulder"], states: ["tension", "stagnation"],
    minCurrentStateMatches: 2,
    anyClues: ["muscle_cramp"],
    requiredTextTerms: ["けいれん", "痙攣", "つる", "こむら返り"], explicitTerms: ["芍薬甘草湯"],
    direction: "急な筋肉のけいれん・痛みかを確認する",
    why: "慢性的な痛み全般ではなく、急な筋肉のけいれんを伴う痛みが入力された時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた痛み方、1日量、服用期間、甘草を含む他製品との重複を確認します。",
    caution: "甘草量が多い処方です。連用を避け、他の甘草含有製品との重複に特に注意してください。",
    ingredientIds: ["formula_shakuyakukanzoto", "peony_root", "licorice_root"],
  }),
  C({
    id: "kampo-ninjinyoueito", type: "kampo", productClass: "第2類医薬品",
    title: "人参養栄湯", query: "人参養栄湯 第2類医薬品",
    symptoms: ["fatigue", "digestion"], states: ["energy_low", "recovery_low", "cold"], avoidStates: ["heat"],
    minCurrentStateMatches: 2, persistentOnly: true, anyClues: ["after_illness", "night_sweats"],
    answerConditions: [{ field: "reserve", values: ["low"] }],
    direction: "病後・術後の体力低下や寝汗を含めて確認する",
    why: "体力虚弱に、病後・術後の体力低下、寝汗、食欲不振、手足の冷えなどが重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた体力低下の背景、食欲、冷え、寝汗、剤形、甘草の重複を確認します。",
    caution: "甘草を含みます。治療中・服薬中、病後・術後、妊娠中は医師・薬剤師等へ確認してください。",
    ingredientIds: ["formula_ninjinyoueito", "ginseng_root", "astragalus_root", "licorice_root", "peony_root"],
  }),
  C({
    id: "kampo-juzentaihoto", type: "kampo", productClass: "第2類医薬品",
    title: "十全大補湯", query: "十全大補湯 第2類医薬品",
    symptoms: ["fatigue", "digestion"], states: ["energy_low", "recovery_low", "cold"], avoidStates: ["heat"],
    minCurrentStateMatches: 2, persistentOnly: true, anyClues: ["after_illness"],
    answerConditions: [{ field: "reserve", values: ["low"] }],
    direction: "病後・術後の衰弱と疲労を確認する",
    why: "体力虚弱で、病後・術後の体力低下や疲労倦怠が続く時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた体力傾向、病後・術後か、食欲、冷え、剤形、甘草の重複を確認します。",
    caution: "甘草を含みます。治療中・服薬中、病後・術後、妊娠中は医師・薬剤師等へ確認してください。",
    ingredientIds: ["formula_juzentaihoto", "ginseng_root", "astragalus_root", "licorice_root", "peony_root"],
  }),
  C({
    id: "kampo-ninjinto", type: "kampo", productClass: "第2類医薬品",
    title: "人参湯", query: "人参湯 第2類医薬品",
    symptoms: ["digestion", "fatigue"], states: ["cold", "digestive_weak", "energy_low"], avoidStates: ["heat"],
    minCurrentStateMatches: 2, anyClues: ["cold_diarrhea", "epigastric_nausea"],
    answerConditions: [{ field: "reserve", values: ["low"] }],
    direction: "体力虚弱・手足の冷え・胃腸症状を確認する",
    why: "体力虚弱と手足の冷えに、下痢・嘔吐・胃痛などの胃腸症状が重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた体力、冷え、便通・胃痛、剤形、甘草の重複を確認します。",
    caution: "甘草を含みます。発熱、血便、強い腹痛、脱水がある場合は服用より受診を優先してください。",
    ingredientIds: ["formula_ninjinto", "ginseng_root", "licorice_root", "ginger"],
  }),
  C({
    id: "kampo-hangeshashinto", type: "kampo", productClass: "第2類医薬品",
    title: "半夏瀉心湯", query: "半夏瀉心湯 第2類医薬品",
    symptoms: ["digestion"], states: ["digestive_weak", "damp", "stagnation"],
    minCurrentStateMatches: 2, anyClues: ["epigastric_nausea", "bowel_rumbling_diarrhea"],
    direction: "みぞおちのつかえ・悪心・腹鳴・軟便を確認する",
    why: "みぞおちのつかえ感に、悪心、腹鳴、軟便・下痢などが重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれたみぞおち、悪心、便通、体力傾向、剤形、甘草の重複を確認します。",
    caution: "甘草を含みます。血便、発熱、強い腹痛、繰り返す嘔吐がある場合は受診を優先してください。",
    ingredientIds: ["formula_hangeshashinto", "ginseng_root", "licorice_root", "ginger"],
  }),
  C({
    id: "kampo-hangebyakujutsutemmato", type: "kampo", productClass: "第2類医薬品",
    title: "半夏白朮天麻湯", query: "半夏白朮天麻湯 第2類医薬品",
    symptoms: ["dizziness", "headache", "digestion"], states: ["digestive_weak", "cold", "damp", "energy_low"],
    minCurrentStateMatches: 3, minSymptomMatches: 2, persistentOnly: true, anyClues: ["cold_unsteady", "standing_dizzy_palpitations"],
    direction: "胃腸虚弱・下肢の冷え・めまいを確認する",
    why: "胃腸の弱りと下肢の冷えに、頭痛・頭重・立ちくらみ・めまいが重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた胃腸、下肢の冷え、めまい方、体力傾向、剤形を確認します。",
    caution: "新しいめまい、歩けないほどのふらつき、急な聞こえの低下、神経症状がある場合は受診を優先してください。",
    ingredientIds: ["formula_hangebyakujutsutemmato", "ginseng_root", "astragalus_root", "ginger"],
  }),
  C({
    id: "kampo-ryokeijutsukanto", type: "kampo", productClass: "第2類医薬品",
    title: "苓桂朮甘湯", query: "苓桂朮甘湯 第2類医薬品",
    symptoms: ["dizziness", "headache", "mood"], states: ["damp", "stagnation", "tension"],
    minCurrentStateMatches: 1, persistentOnly: true, anyClues: ["standing_dizzy_palpitations"],
    direction: "立ちくらみ・めまい・動悸の組み合わせを確認する",
    why: "立ちくらみやめまいに、動悸などが重なる追加回答から適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた体力傾向、めまい方、動悸、尿量、剤形、甘草の重複を確認します。",
    caution: "甘草を含みます。失神、胸痛、強い動悸、急な神経症状を伴う場合は受診を優先してください。",
    ingredientIds: ["formula_ryokeijutsukanto", "licorice_root"],
  }),
  C({
    id: "kampo-shimbuto", type: "kampo", productClass: "第2類医薬品",
    title: "真武湯", query: "真武湯 第2類医薬品",
    symptoms: ["fatigue", "dizziness", "swelling", "digestion"], states: ["cold", "energy_low", "damp", "digestive_weak"],
    minCurrentStateMatches: 3, persistentOnly: true, anyClues: ["cold_diarrhea", "cold_unsteady"],
    answerConditions: [{ field: "reserve", values: ["low"] }],
    direction: "体力低下・冷え・ふらつきや下痢を確認する",
    why: "体力低下と冷えに、ふらつき・めまい・下痢などが重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた体力、冷え、便通、ふらつき、剤形、附子を含む製品の注意を確認します。",
    caution: "附子を含む処方です。動悸、のぼせ、舌のしびれ、悪心などが出た場合は中止し、治療中・服薬中は専門家へ確認してください。",
    ingredientIds: ["formula_shimbuto", "processed_aconite", "peony_root", "ginger"],
  }),
  C({
    id: "kampo-tokishigyakukagoshuyushokyoto", type: "kampo", productClass: "第2類医薬品",
    title: "当帰四逆加呉茱萸生姜湯", query: "当帰四逆加呉茱萸生姜湯 第2類医薬品",
    symptoms: ["fatigue", "headache", "low_back_pain"], states: ["cold", "energy_low", "stagnation"], avoidStates: ["heat"],
    minCurrentStateMatches: 2, persistentOnly: true, anyClues: ["strong_extremity_cold"],
    direction: "下肢を中心とした強い手足の冷えを確認する",
    why: "手足、とくに下肢の冷えが強く、頭痛・腰痛・下腹部痛などが重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた冷えの部位、痛み、体力傾向、胃腸状態、剤形、甘草の重複を確認します。",
    caution: "甘草を含みます。胃腸が弱い人、高齢者、妊娠中、治療中・服薬中は専門家へ確認してください。",
    ingredientIds: ["formula_tokishigyakukagoshuyushokyoto", "peony_root", "licorice_root", "ginger"],
  }),
  C({
    id: "kampo-dokkatsukakkonto", type: "kampo", productClass: "第2類医薬品",
    title: "独活葛根湯", query: "独活葛根湯 第2類医薬品",
    symptoms: ["neck_shoulder"], states: ["tension", "stagnation"],
    minCurrentStateMatches: 2, persistentOnly: true,
    direction: "慢性的な肩こり・寝違え等として確認する",
    why: "急なかぜの初期ではなく、肩こり・寝違え・四十肩・五十肩として適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた肩の状態、体力傾向、剤形、麻黄・甘草を含む他製品との重複を確認します。",
    caution: "麻黄・甘草を含みます。高血圧、心疾患、甲状腺疾患、排尿困難、治療中・服薬中の場合は薬剤師等へ確認してください。",
    ingredientIds: ["formula_dokkatsukakkonto", "ephedra_herb", "licorice_root", "kudzu_root", "ginger"],
  }),
  C({
    id: "kampo-nijutsuto", type: "kampo", productClass: "第2類医薬品",
    title: "二朮湯", query: "二朮湯 第2類医薬品",
    symptoms: ["neck_shoulder"], states: ["damp", "stagnation", "tension"],
    minCurrentStateMatches: 2, persistentOnly: true, anyClues: ["shoulder_arm_pain"],
    direction: "肩から上腕にかけての痛みを確認する",
    why: "肩から上腕にかけた痛みが続く追加回答から、四十肩・五十肩の適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた痛む範囲、体力傾向、剤形、甘草を含む他製品との重複を確認します。",
    caution: "甘草を含みます。外傷、急な筋力低下、しびれ、強い夜間痛がある場合は原因確認を優先してください。",
    ingredientIds: ["formula_nijutsuto", "licorice_root", "ginger"],
  }),
  C({
    id: "kampo-keishikaryukotsuboreito", type: "kampo", productClass: "第2類医薬品",
    title: "桂枝加竜骨牡蛎湯", query: "桂枝加竜骨牡蛎湯 第2類医薬品",
    symptoms: ["sleep", "mood", "fatigue"], states: ["tension", "energy_low", "recovery_low"],
    minCurrentStateMatches: 2, persistentOnly: true, anyClues: ["sensitive_palpitations"],
    direction: "疲れやすさ・神経過敏・不眠を確認する",
    why: "疲れやすさに、神経過敏・興奮しやすさ・動悸・不眠が重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた体力、神経過敏、不眠、動悸、剤形、甘草の重複を確認します。",
    caution: "甘草を含みます。胸痛、強い動悸、失神、長引く不眠がある場合は受診も検討してください。",
    ingredientIds: ["formula_keishikaryukotsuboreito", "licorice_root", "ginger"],
  }),
  C({
    id: "kampo-yokukansankachimpihange", type: "kampo", productClass: "第2類医薬品",
    title: "抑肝散加陳皮半夏", query: "抑肝散加陳皮半夏 第2類医薬品",
    symptoms: ["mood", "sleep", "digestion"], states: ["tension", "digestive_weak", "recovery_low"],
    minCurrentStateMatches: 2, persistentOnly: true, anyClues: ["irritable"],
    direction: "神経過敏・いらだちと胃腸の弱りを確認する",
    why: "神経過敏やいらだちに、睡眠の乱れや胃腸の弱りが重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた体力、神経過敏、胃腸、睡眠、剤形、甘草の重複を確認します。",
    caution: "甘草を含みます。高齢者、治療中・服薬中、妊娠中は専門家へ確認してください。",
    ingredientIds: ["formula_yokukansankachimpihange", "licorice_root"],
  }),
  C({
    id: "kampo-heisan", type: "kampo", productClass: "第2類医薬品",
    title: "平胃散", query: "平胃散 第2類医薬品",
    symptoms: ["digestion"], states: ["digestive_weak", "damp"],
    minCurrentStateMatches: 2, persistentOnly: true,
    answerConditions: [{ field: "digestion", values: ["postmeal_heavy", "appetite_low"] }],
    direction: "食欲不振・食後の胃もたれを確認する",
    why: "食欲不振や食後の重さが続く回答から、胃もたれ・消化不良等の適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた胃もたれ、食欲、便通、体力傾向、剤形、甘草の重複を確認します。",
    caution: "甘草を含みます。体重減少、黒い便、吐血、強い腹痛がある場合は受診を優先してください。",
    ingredientIds: ["formula_heisan", "licorice_root", "ginger"],
  }),
  C({
    id: "kampo-keishikashakuyakuto", type: "kampo", productClass: "第2類医薬品",
    title: "桂枝加芍薬湯", query: "桂枝加芍薬湯 第2類医薬品",
    symptoms: ["digestion"], states: ["digestive_weak", "stagnation"],
    minCurrentStateMatches: 2, allowedDurations: ["days", "weeks", "months"], anyClues: ["abdominal_pain_bloat"],
    direction: "腹部膨満感・腹痛・便通変化を確認する",
    why: "腹部膨満感や腹痛に、便通の変化が重なる追加回答から適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた腹部膨満・腹痛・便通、体力傾向、剤形、甘草の重複を確認します。",
    caution: "甘草を含みます。発熱、血便、繰り返す嘔吐、強い腹痛がある場合は受診を優先してください。",
    ingredientIds: ["formula_keishikashakuyakuto", "peony_root", "licorice_root", "ginger"],
  }),
];

export const INGREDIENT_LINKS = {
  coix_seed: { label: "ヨクイニン／ハトムギ", note: "健康食品と漢方薬では区分・目的・表示が異なります。" },
  ginger: { label: "生姜", note: "健康飲料のしょうがと、漢方処方中の生薬は区分して確認します。" },
  ginseng_root: { label: "人参／高麗人参", note: "健康食品と漢方処方では量・組み合わせ・目的が異なります。" },
  licorice_root: { label: "甘草", note: "複数の漢方薬や生薬製品で重複しやすい成分です。" },
  peony_root: { label: "芍薬", note: "処方全体の組み合わせで使われるため、単独成分と同一視しません。" },
  ephedra_herb: { label: "麻黄", note: "心疾患・高血圧・甲状腺疾患などで特に確認が必要です。" },
  astragalus_root: { label: "黄耆", note: "健康食品と漢方処方中の生薬では位置付けが異なります。" },
  turmeric_rhizome: { label: "ウコン", note: "原料部位・抽出物・クルクミン表示を分けて確認します。" },
  ginkgo_leaf: { label: "イチョウ葉", note: "原料表示と、出血リスクに関係する薬との併用確認が重要です。" },
  maca_root: { label: "マカ", note: "原料量と同時配合成分を確認します。" },
  kudzu_root: { label: "葛根", note: "食品素材と葛根湯など処方中の生薬では目的・組み合わせが異なります。" },
  eucommia_leaf: { label: "杜仲葉", note: "杜仲葉の健康茶と、生薬として使われる樹皮を区分します。" },
  eleuthero_root: { label: "エゾウコギ", note: "根・根茎由来の原料名、抽出物か粉末か、同時配合成分を確認します。" },
  notoginseng_root: { label: "田七人参", note: "オタネニンジンとは別素材です。抗凝固薬等との併用確認が重要です。" },
  black_ginger: { label: "ブラックジンジャー", note: "通常の生姜とは別素材で、商品ごとの届出機能を確認します。" },
  mulberry_leaf: { label: "桑葉", note: "健康茶と機能性表示食品では、表示できる機能と関与成分が異なります。" },
  goji_fruit: { label: "クコの実", note: "通常食品と濃縮製品を分け、服薬中は相互作用を確認します。" },
  processed_aconite: { label: "加工ブシ", note: "附子を含む処方は、体力・冷えの状態と使用上の注意を特に確認します。" },
};
