/**
 * 「悩みから探す」で使う比較候補マスター。
 *
 * 未病レーダーのショップは、対症療法の一般用医薬品ではなく、
 * 続けやすいケア用品・健康食品等と、状態像が合う漢方薬を扱う。
 * 候補理由（why）と商品を選ぶ時の確認（compare）は混ぜない。
 */

export const GUIDED_SCOPE_OPTIONS = [
  { key: "all", label: "まとめて見る", oral: true },
  { key: "selfcare", label: "ケア用品", oral: false },
  { key: "health", label: "健康食品・サプリ", oral: true },
  { key: "kampo", label: "漢方薬", oral: true },
];

export const GUIDED_SCOPE_META = {
  selfcare: { label: "ケア用品", eyebrow: "今日から使う", tone: "mint" },
  health: { label: "健康食品・サプリ", eyebrow: "続け方から選ぶ", tone: "gold" },
  kampo: { label: "漢方薬", eyebrow: "状態の組み合わせから選ぶ", tone: "violet" },
};

const C = (candidate) => ({
  answerConditions: [],
  avoidStates: [],
  caution: "",
  compare: "",
  explicitOnly: false,
  explicitTerms: [],
  ingredientIds: [],
  minCurrentStateMatches: 0,
  minSymptomMatches: 1,
  persistentOnly: false,
  requiredTextTerms: [],
  ...candidate,
});

export const GUIDED_CANDIDATES = [
  // ケア用品：一時的な「今日の状態」だけでも候補にできる。
  C({
    id: "care-warm-pack", type: "selfcare", productClass: "ケア用品",
    title: "繰り返し使える温熱パック", query: "温熱パック 電子レンジ 繰り返し",
    symptoms: ["fatigue", "digestion", "neck_shoulder", "low_back_pain"], states: ["cold", "tension", "stagnation"],
    minCurrentStateMatches: 1, direction: "冷えやこわばりを短く温める",
    why: "冷えやこわばりがあり、温めると少し楽になる時に使う場所と時間を調整しやすい用品です。",
    compare: "対応部位、温度の段階、加熱時間、カバーを洗えるかを比べます。",
    caution: "熱感・腫れ・急な痛みがある場所には使わず、低温やけどに注意してください。",
  }),
  C({
    id: "care-neck-pillow", type: "selfcare", productClass: "ケア用品",
    title: "首肩用の温冷ケアパッド", query: "首肩 温冷 ケア パッド",
    symptoms: ["neck_shoulder", "headache"], states: ["tension", "stagnation", "heat", "cold"],
    minCurrentStateMatches: 1, direction: "首肩の状態に合わせて温冷を選ぶ",
    why: "首肩の張りや熱感・冷えがあり、同じ刺激を続けず温冷を選びたい時の用品です。",
    compare: "温冷両用か、重さ、固定方法、肌に当たる面を洗えるかを比べます。",
    caution: "突然の激しい頭痛、しびれ、麻痺がある場合はセルフケアを優先しません。",
  }),
  C({
    id: "care-leg-release", type: "selfcare", productClass: "ケア用品",
    title: "脚用のやさしいリリース用品", query: "ふくらはぎ マッサージ ローラー やわらか",
    symptoms: ["swelling", "fatigue"], states: ["damp", "stagnation", "tension"],
    minCurrentStateMatches: 1, direction: "脚の重さをためない",
    why: "脚の重さやむくみ感があり、強く押さずに短時間動かすきっかけを作りたい時の用品です。",
    compare: "硬さ、持ちやすさ、圧を調節できる形、洗いやすさを比べます。",
    caution: "片脚だけの急な腫れ・熱・痛みがある時は使用せず、受診を優先してください。",
  }),
  C({
    id: "care-sleep-light", type: "selfcare", productClass: "ケア用品",
    title: "光を減らす睡眠環境用品", query: "遮光 アイマスク 睡眠",
    symptoms: ["sleep", "headache", "fatigue"], states: ["tension", "recovery_low", "heat"],
    minCurrentStateMatches: 1, direction: "夜の光刺激を減らす",
    why: "睡眠の乱れや休みにくさがあり、眠る前の光を減らす環境づくりが合う候補です。",
    compare: "遮光性、締め付け、寝返り時のずれにくさ、洗いやすさを比べます。",
  }),
  C({
    id: "care-humid-meter", type: "selfcare", productClass: "ケア用品",
    title: "温湿度計", query: "温湿度計 デジタル 室内",
    symptoms: ["sleep", "fatigue", "headache", "dizziness", "swelling"], states: ["damp", "dry", "heat", "cold"],
    minCurrentStateMatches: 1, direction: "室内の温度と湿度を見える化する",
    why: "湿気・乾燥・暑さ・冷えの体感があり、まず室内環境を数値で確かめたい時の用品です。",
    compare: "表示の見やすさ、最高・最低値、置き方、複数部屋で使えるかを比べます。",
  }),
  C({
    id: "care-lumbar-support", type: "selfcare", productClass: "ケア用品",
    title: "姿勢を変えやすい腰サポート", query: "腰 クッション 姿勢 サポート",
    symptoms: ["low_back_pain", "fatigue"], states: ["tension", "stagnation"],
    minCurrentStateMatches: 1, direction: "同じ姿勢を続けない",
    why: "腰の張りや重さがあり、座り姿勢を一つに固定せず切り替えたい時の用品です。",
    compare: "椅子との寸法、硬さ、固定方法、長時間座って圧が集中しないかを比べます。",
    caution: "強い痛みや脚のしびれ、排尿・排便の異常がある場合は受診を優先してください。",
  }),

  // 健康食品・サプリ：継続する状態、または成分名の明示がある時だけ候補にする。
  C({
    id: "health-ginger-drink", type: "health", productClass: "健康飲料",
    title: "しょうがを使った健康飲料", query: "しょうが 健康飲料",
    symptoms: ["fatigue", "digestion", "neck_shoulder"], states: ["cold", "digestive_weak"], avoidStates: ["heat"],
    minCurrentStateMatches: 2, explicitTerms: ["しょうが", "生姜", "ジンジャー"], direction: "冷たい飲み物の連続を切る",
    why: "冷えと胃腸の負担が重なり、温かい飲み物へ切り替える選択肢を持ちたい時の候補です。",
    compare: "しょうがの表示、糖分、カフェイン、1回量、毎日続けられる味かを比べます。",
    caution: "辛味で胃がつらくなる人や、治療中・服薬中の人は原材料と取り方を確認してください。",
    ingredientIds: ["ginger"],
  }),
  C({
    id: "health-evening-herbal-tea", type: "health", productClass: "健康茶",
    title: "夜向けのノンカフェイン健康茶", query: "ノンカフェイン ハーブティー",
    symptoms: ["sleep", "mood"], states: ["tension", "recovery_low"],
    minCurrentStateMatches: 2, direction: "夜の飲み物から刺激を減らす",
    why: "睡眠や気分の負担と休みにくさが重なり、夕方以降の飲み物を切り替えたい時の候補です。",
    compare: "カフェイン表示、使用原料、香り、抽出時間、毎日続けられる量を比べます。",
    caution: "ハーブや生薬を含む商品は、妊娠・授乳中、治療中・服薬中、アレルギー歴がある場合に原材料を確認してください。",
  }),
  C({
    id: "health-nutrition-drink", type: "health", productClass: "栄養補助飲料",
    title: "食事を補う栄養補助飲料", query: "栄養補助飲料 ノンカフェイン",
    symptoms: ["fatigue", "digestion", "dizziness"], states: ["energy_low", "digestive_weak", "recovery_low"],
    minCurrentStateMatches: 2,
    answerConditions: [{ field: "digestion", values: ["appetite_low"] }],
    direction: "食べられない日の不足を重ねない",
    why: "疲れやすさに食欲低下が重なり、通常の食事を取りにくい日の補助を探す条件です。",
    compare: "エネルギー量、たんぱく質、糖質、カフェイン、アレルゲン、飲み切れる量を比べます。",
    caution: "食欲低下が続く、体重が減る、食事制限がある場合は商品選びより原因確認を優先してください。",
  }),
  C({
    id: "health-ginseng", type: "health", productClass: "生薬系健康食品",
    title: "高麗人参（オタネニンジン）", query: "高麗人参 健康食品",
    symptoms: ["fatigue"], states: ["energy_low", "cold"], avoidStates: ["heat", "tension"],
    minCurrentStateMatches: 2, persistentOnly: true, explicitTerms: ["高麗人参", "オタネニンジン", "人参サプリ"],
    direction: "疲れやすさが続く時の健康食品を比較する",
    why: "疲れやすさが続き、体力低下と冷えが重なる場合に、生薬系健康食品として比較する候補です。",
    compare: "使用部位、抽出物か粉末か、1日量、同時配合成分、カフェインの有無を比べます。",
    caution: "不眠・動悸がある人、血圧・血糖の治療中、抗凝固薬などを使用中の人は専門家へ確認してください。",
    ingredientIds: ["ginseng_root"],
  }),
  C({
    id: "health-coix", type: "health", productClass: "生薬系健康食品",
    title: "ハトムギ由来の健康食品", query: "ハトムギ 健康食品",
    symptoms: ["swelling"], states: ["damp"], minCurrentStateMatches: 1, persistentOnly: true,
    explicitTerms: ["ハトムギ", "ヨクイニン"], direction: "重さやむくみ感が続く時の素材を比較する",
    why: "むくみ感と重さがしばらく続く場合に、ハトムギ由来の健康食品を比較する候補です。",
    compare: "食品・健康食品・医薬品の区分、使用部位、1日量、ほかの原料との組み合わせを比べます。",
    caution: "むくみの治療代わりにはしません。妊娠中、片脚だけの腫れ、息苦しさを伴う場合は自己判断で使わないでください。",
    ingredientIds: ["coix_seed"],
  }),
  C({
    id: "health-duzhong", type: "health", productClass: "健康茶",
    title: "杜仲葉を使った健康茶", query: "杜仲茶",
    symptoms: ["fatigue", "swelling"], states: ["damp", "energy_low"],
    explicitOnly: true, explicitTerms: ["杜仲", "杜仲茶", "杜仲葉"], direction: "杜仲葉の健康茶を区分して比較する",
    why: "杜仲を調べたいという入力がある場合に、樹皮を使う生薬とは区別して健康茶を比較します。",
    compare: "杜仲葉の表示、単一原料かブレンドか、カフェイン、抽出方法、1日量を比べます。",
    caution: "治療中・服薬中、妊娠・授乳中は使用前に専門家へ確認してください。",
    ingredientIds: ["eucommia_leaf"],
  }),
  C({
    id: "health-heme-iron", type: "health", productClass: "サプリメント",
    title: "ヘム鉄", query: "ヘム鉄 サプリ",
    symptoms: ["fatigue", "dizziness"], states: ["energy_low", "recovery_low"],
    explicitOnly: true, explicitTerms: ["ヘム鉄", "鉄サプリ"], direction: "鉄を補う前に必要性と重複を確認する",
    why: "ヘム鉄・鉄サプリを調べたいという入力があるため、体感だけで不足と決めず比較対象にします。",
    compare: "1日量、鉄以外の配合成分、ほかのサプリとの重複、続けやすい剤形を比べます。",
    caution: "疲れやめまいだけで鉄不足とは判断できません。強い症状、妊娠中、治療中は検査や専門家確認を優先してください。",
    ingredientIds: ["iron"],
  }),
  C({
    id: "health-magnesium", type: "health", productClass: "サプリメント",
    title: "マグネシウム", query: "マグネシウム サプリ",
    symptoms: ["sleep", "neck_shoulder", "mood", "headache"], states: ["tension", "recovery_low"],
    explicitOnly: true, explicitTerms: ["マグネシウム"], direction: "不足を決めつけず成分を比較する",
    why: "マグネシウムを調べたいという入力があるため、症状だけで不足と決めず比較対象にします。",
    compare: "1日量、化合物の種類、ほかのサプリとの重複、摂取回数を比べます。",
    caution: "下痢を起こすことがあります。腎機能低下や治療中・服薬中の場合は事前に専門家へ確認してください。",
    ingredientIds: ["magnesium"],
  }),
  C({
    id: "health-b-vitamins", type: "health", productClass: "サプリメント",
    title: "ビタミンB群", query: "ビタミンB群 サプリ",
    symptoms: ["fatigue", "digestion"], states: ["energy_low", "recovery_low"],
    explicitOnly: true, explicitTerms: ["ビタミンB", "B群サプリ"], direction: "食事と他製品の重複を確認する",
    why: "ビタミンB群を調べたいという入力があるため、食事状況と重複を確認する比較対象にします。",
    compare: "各ビタミンの1日量、単一成分か複合か、栄養ドリンクやマルチビタミンとの重複を比べます。",
    caution: "複数製品を併用する場合は、同じビタミンを重ねていないか確認してください。",
    ingredientIds: ["vitamin_b_group"],
  }),
  C({
    id: "health-ginkgo", type: "health", productClass: "植物由来サプリ",
    title: "イチョウ葉エキス", query: "イチョウ葉 サプリ",
    symptoms: ["dizziness", "mood"], states: ["stagnation"],
    explicitOnly: true, explicitTerms: ["イチョウ葉", "銀杏葉"], direction: "目的と安全条件を確認して比較する",
    why: "イチョウ葉を調べたいという入力があるため、症状の治療代わりにせず比較対象にします。",
    compare: "原料表示、抽出物の表示、1日量、同時配合成分を比べます。",
    caution: "出血リスクに関係する薬との相互作用があります。めまいが続く場合は原因確認を優先してください。",
    ingredientIds: ["ginkgo_leaf"],
  }),
  C({
    id: "health-turmeric", type: "health", productClass: "植物由来サプリ",
    title: "ウコン由来の健康食品", query: "ウコン サプリ",
    symptoms: ["digestion", "fatigue"], states: ["stagnation"],
    explicitOnly: true, explicitTerms: ["ウコン", "クルクミン"], direction: "飲酒対策と決めつけず比較する",
    why: "ウコン・クルクミンを調べたいという入力があるため、利用目的を確認する比較対象にします。",
    compare: "原料部位、クルクミンの表示、1日量、同時配合成分を比べます。",
    caution: "胆道疾患・肝疾患がある人、抗凝固薬などを使用中の人は自己判断で使わないでください。",
    ingredientIds: ["turmeric_rhizome"],
  }),
  C({
    id: "health-maca", type: "health", productClass: "植物由来サプリ",
    title: "マカ", query: "マカ サプリ",
    symptoms: ["fatigue", "mood"], states: ["energy_low"],
    explicitOnly: true, explicitTerms: ["マカ"], direction: "商品名の印象ではなく中身を比較する",
    why: "マカを調べたいという入力があるため、疲労の原因を決めつけず比較対象にします。",
    compare: "マカ原料の1日量、抽出物か粉末か、同時配合成分、カフェインの有無を比べます。",
    caution: "妊娠・授乳中、治療中、ホルモンに関係する疾患がある場合は専門家へ確認してください。",
    ingredientIds: ["maca_root"],
  }),

  // 漢方薬：現在の複数条件が処方像と重なる場合だけ候補にする。
  C({
    id: "kampo-hochuekkito", type: "kampo", productClass: "第2類医薬品",
    title: "補中益気湯", query: "補中益気湯 第2類医薬品",
    symptoms: ["fatigue", "digestion"], states: ["energy_low", "digestive_weak", "recovery_low"], avoidStates: ["heat"],
    minCurrentStateMatches: 2, persistentOnly: true,
    answerConditions: [{ field: "reserve", values: ["low"] }, { field: "digestion", values: ["appetite_low", "postmeal_heavy"] }],
    direction: "疲れやすさと胃腸の弱りを一緒に確認する",
    why: "疲れやすさ、体力低下、食欲・胃腸の弱りが重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた体力傾向、1日量、剤形、甘草を含む他製品との重複を確認します。",
    caution: "甘草を含みます。高血圧、むくみ、心・腎疾患、治療中・服薬中の場合は薬剤師等へ確認してください。",
    ingredientIds: ["formula_hochuekkito", "licorice_root", "ginseng_root", "astragalus_root"],
  }),
  C({
    id: "kampo-rikkunshito", type: "kampo", productClass: "第2類医薬品",
    title: "六君子湯", query: "六君子湯 第2類医薬品",
    symptoms: ["digestion", "fatigue"], states: ["digestive_weak", "energy_low", "damp"],
    minCurrentStateMatches: 2,
    answerConditions: [{ field: "digestion", values: ["appetite_low", "postmeal_heavy"] }],
    direction: "胃腸の弱りと食欲を確認する",
    why: "胃腸の不調に、食欲低下・食後の重さと体力低下が重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた胃腸症状と体力傾向、剤形、1日量、甘草の重複を確認します。",
    caution: "甘草を含みます。治療中・服薬中、持病がある場合は薬剤師等へ確認してください。",
    ingredientIds: ["formula_rikkunshito", "licorice_root", "ginseng_root"],
  }),
  C({
    id: "kampo-goreisan", type: "kampo", productClass: "第2類医薬品",
    title: "五苓散", query: "五苓散 第2類医薬品",
    symptoms: ["swelling", "headache", "dizziness"], states: ["damp"], avoidStates: ["dry"],
    minCurrentStateMatches: 1,
    requiredTextTerms: ["口渇", "のどが渇", "喉が渇", "尿が少ない", "水を飲むと吐"],
    explicitTerms: ["五苓散"], direction: "水分の偏りと口渇・尿量を確認する",
    why: "むくみ・頭痛・めまいだけでなく、口渇や尿量など水分の偏りを示す入力がある時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた口渇・尿量等の条件、剤形、1日量を確認します。",
    caution: "長引くめまい・頭痛・嘔吐、急なむくみは商品探しより原因確認を優先してください。",
    ingredientIds: ["formula_goreisan"],
  }),
  C({
    id: "kampo-boiogito", type: "kampo", productClass: "第2類医薬品",
    title: "防已黄耆湯", query: "防已黄耆湯 第2類医薬品",
    symptoms: ["swelling", "fatigue"], states: ["damp", "energy_low"],
    minCurrentStateMatches: 2, persistentOnly: true,
    requiredTextTerms: ["汗をかきやすい", "汗かき"], explicitTerms: ["防已黄耆湯"],
    direction: "むくみ・疲れやすさ・汗のかき方を確認する",
    why: "むくみ感、疲れやすさ、汗をかきやすい体力傾向が重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた体力・汗・むくみの条件、剤形、甘草の重複を確認します。",
    caution: "甘草を含みます。高血圧、心・腎疾患、治療中・服薬中の場合は薬剤師等へ確認してください。",
    ingredientIds: ["formula_boiogito", "licorice_root", "astragalus_root"],
  }),
  C({
    id: "kampo-kamikihito", type: "kampo", productClass: "第2類医薬品",
    title: "加味帰脾湯", query: "加味帰脾湯 第2類医薬品",
    symptoms: ["sleep", "mood", "fatigue"], states: ["energy_low", "recovery_low", "tension"],
    minCurrentStateMatches: 2, minSymptomMatches: 2, persistentOnly: true,
    direction: "疲労・不安感・睡眠をまとめて確認する",
    why: "心身の疲れに、睡眠の乱れや不安感が複数重なる時に体力傾向と適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた精神症状と体力傾向、剤形、甘草の重複を確認します。",
    caution: "甘草を含みます。妊娠中、治療中・服薬中の場合は薬剤師等へ確認してください。",
    ingredientIds: ["formula_kamikihito", "licorice_root", "ginseng_root", "astragalus_root"],
  }),
  C({
    id: "kampo-sansoninto", type: "kampo", productClass: "第2類医薬品",
    title: "酸棗仁湯", query: "酸棗仁湯 第2類医薬品",
    symptoms: ["sleep", "fatigue"], states: ["recovery_low", "energy_low", "tension"],
    minCurrentStateMatches: 2, minSymptomMatches: 1, persistentOnly: true,
    answerConditions: [{ field: "reserve", values: ["low"] }],
    direction: "疲れているのに眠れない状態を確認する",
    why: "睡眠の乱れに、疲れや体力低下が続く状態が重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた不眠と体力傾向、剤形、1日量、甘草の重複を確認します。",
    caution: "甘草を含む製品があります。長引く不眠や日中機能低下は受診も検討してください。",
    ingredientIds: ["formula_sansoninto", "licorice_root"],
  }),
  C({
    id: "kampo-hangekobokuto", type: "kampo", productClass: "第2類医薬品",
    title: "半夏厚朴湯", query: "半夏厚朴湯 第2類医薬品",
    symptoms: ["mood", "digestion", "sleep"], states: ["tension", "stagnation"],
    minCurrentStateMatches: 2,
    requiredTextTerms: ["喉がつかえる", "のどがつかえる", "喉の異物感", "梅核気"], explicitTerms: ["半夏厚朴湯"],
    direction: "喉のつかえ感と気分の緊張を確認する",
    why: "気分の負担に、喉や食道部のつかえ感が重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた喉のつかえ感と体力傾向、剤形、1日量を確認します。",
    caution: "飲み込みづらさが続く、体重減少、胸痛がある場合は自己判断を避けてください。",
    ingredientIds: ["formula_hangekobokuto", "ginger"],
  }),
  C({
    id: "kampo-anchusan", type: "kampo", productClass: "第2類医薬品",
    title: "安中散", query: "安中散 第2類医薬品",
    symptoms: ["digestion"], states: ["cold", "digestive_weak"], avoidStates: ["heat"],
    minCurrentStateMatches: 2,
    answerConditions: [{ field: "digestion", values: ["appetite_low", "postmeal_heavy"] }],
    direction: "冷えを伴う胃の不調を確認する",
    why: "胃腸の不調に、冷えと食欲・食後の変化が重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた胃痛・胸やけ等の症状、体力傾向、甘草の重複を確認します。",
    caution: "黒い便、吐血、強い腹痛がある場合は受診を優先してください。",
    ingredientIds: ["formula_anchusan", "licorice_root"],
  }),
  C({
    id: "kampo-kakkonto", type: "kampo", productClass: "第2類医薬品",
    title: "葛根湯", query: "葛根湯 第2類医薬品",
    symptoms: ["neck_shoulder", "headache"], states: ["cold", "tension"], avoidStates: ["heat", "energy_low"],
    minCurrentStateMatches: 2, allowedDurations: ["today", "days"],
    requiredTextTerms: ["寒気", "ぞくぞく", "風邪", "かぜ"], explicitTerms: ["葛根湯"],
    direction: "急な寒気と首肩のこわばりを確認する",
    why: "慢性的な肩こりではなく、急な寒気・かぜの初期と首肩のこわばりが重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた発症時期・発汗・体力傾向、麻黄・甘草の重複を確認します。",
    caution: "麻黄・甘草を含みます。高血圧、心疾患、甲状腺疾患、排尿困難、治療中・服薬中の場合は薬剤師等へ確認してください。",
    ingredientIds: ["formula_kakkonto", "ephedra_herb", "licorice_root", "ginger", "kudzu_root"],
  }),
  C({
    id: "kampo-tokishakuyakusan", type: "kampo", productClass: "第2類医薬品",
    title: "当帰芍薬散", query: "当帰芍薬散 第2類医薬品",
    symptoms: ["dizziness", "swelling", "fatigue"], states: ["cold", "energy_low", "damp"],
    minCurrentStateMatches: 3, minSymptomMatches: 2, persistentOnly: true,
    direction: "冷え・体力・めまい・むくみの組み合わせを確認する",
    why: "冷えと体力低下に、めまい・むくみなどが複数重なる時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた体力・冷え・めまい等の条件、剤形、1日量を確認します。",
    caution: "めまいの原因確認が先です。妊娠中、治療中・服薬中の場合は専門家へ確認してください。",
    ingredientIds: ["formula_tokishakuyakusan", "peony_root"],
  }),
  C({
    id: "kampo-shakuyakukanzoto", type: "kampo", productClass: "第2類医薬品",
    title: "芍薬甘草湯", query: "芍薬甘草湯 第2類医薬品",
    symptoms: ["low_back_pain", "neck_shoulder"], states: ["tension", "stagnation"],
    minCurrentStateMatches: 2,
    requiredTextTerms: ["けいれん", "痙攣", "つる", "こむら返り"], explicitTerms: ["芍薬甘草湯"],
    direction: "急な筋肉のけいれん・痛みかを確認する",
    why: "慢性的な痛み全般ではなく、急な筋肉のけいれんを伴う痛みが入力された時に適応を照合する方剤候補です。",
    compare: "効能・効果に書かれた痛み方、1日量、服用期間、甘草を含む他製品との重複を確認します。",
    caution: "甘草量が多い処方です。連用を避け、他の甘草含有製品との重複に特に注意してください。",
    ingredientIds: ["formula_shakuyakukanzoto", "peony_root", "licorice_root"],
  }),
];

export const INGREDIENT_LINKS = {
  coix_seed: { label: "ヨクイニン／ハトムギ", note: "健康食品と漢方薬では区分・目的・表示が異なります。" },
  ginger: { label: "生姜", note: "健康飲料のしょうがと、漢方処方中の生薬は区分して確認します。" },
  ginseng_root: { label: "人参／高麗人参", note: "健康食品と漢方処方では量・組み合わせ・目的が異なります。" },
  licorice_root: { label: "甘草", note: "複数の漢方薬や生薬製品で重複しやすい成分です。" },
  peony_root: { label: "芍薬", note: "処方全体の組み合わせで使われるため、単独成分と同一視しません。" },
  ephedra_herb: { label: "麻黄", note: "心疾患・高血圧・甲状腺疾患などで特に確認が必要です。" },
  astragalus_root: { label: "黄耆", note: "健康食品と漢方処方中の生薬では位置付けが異なります。" },
  turmeric_rhizome: { label: "ウコン", note: "原料部位・抽出物・クルクミン表示を分けて確認します。" },
  ginkgo_leaf: { label: "イチョウ葉", note: "原料表示と、出血リスクに関係する薬との併用確認が重要です。" },
  maca_root: { label: "マカ", note: "原料量と同時配合成分を確認します。" },
  kudzu_root: { label: "葛根", note: "食品素材と葛根湯など処方中の生薬では目的・組み合わせが異なります。" },
  eucommia_leaf: { label: "杜仲葉", note: "杜仲葉の健康茶と、生薬として使われる樹皮を区分します。" },
};
