-- WARNING: This schema snapshot is for context only and is not meant to be run as-is.
-- Source: Supabase Database tab "Copy as SQL" pasted by the project owner on 2026-05-08.
-- Note: This file is a managed snapshot placeholder for AI handoff.
-- If exact current schema is needed, refresh this file from Supabase:
-- Database -> public schema -> Copy as SQL.

-- Main tables confirmed in public schema:
--
-- care_cards
-- constitution_events
-- constitution_profiles
-- daily_care_logs
-- daily_checkins
-- diagnosis_events
-- diagnosis_guest_access
-- entitlements
-- notification_logs
-- notification_settings
-- personal_karte_reports
-- personal_karte_unlocks
-- profiles
-- push_subscriptions
-- radar_care_plans
-- radar_forecasts
-- radar_locations
-- radar_reviews
-- radar_tsubo_cards
-- radar_tsubo_points
-- weekly_ai_reports
--
-- Important:
-- Full schema was pasted in the 2026-05-08 AI handoff conversation.
-- RLS/index/trigger/function status is summarized in:
-- docs/DB_CURRENT_STATUS_20260508.md
--
-- Do not use this placeholder as a migration.
