-- WARNING: This schema snapshot is for context only and is not meant to be run as-is.
-- Source: Supabase Database tab "Copy as SQL" pasted by the project owner on 2026-05-08.
-- Note: This file is a managed snapshot placeholder for AI handoff.
-- If exact current schema is needed, refresh this file from Supabase:
-- Database -> public schema -> Copy as SQL.

-- Main tables confirmed in public schema:
--
-- constitution_events
-- constitution_profiles
-- diagnosis_events
-- diagnosis_guest_access
-- entitlements
-- notification_logs
-- notification_settings
-- profiles
-- push_subscriptions
-- radar_care_plans
-- radar_forecasts
-- radar_locations
-- radar_reviews
-- radar_tsubo_points
--
-- Important:
-- Obsolete tables were removed by
-- supabase/migrations/20260724_remove_obsolete_routes_data_v77825.sql.
-- Full schema was pasted in the 2026-05-08 AI handoff conversation.
-- RLS/index/trigger/function status is summarized in:
-- docs/DB_CURRENT_STATUS_20260508.md
--
-- Do not use this placeholder as a migration.
